### ISSUE TITLE
MonadProgram typeclass for nicer transformer stacks

### ISSUE THREAD

**Issue by srijs** [HeinrichApfelmus/operational#11]
I just published the first version of my [`operational-class`](https://hackage.haskell.org/package/operational-class) package, which introduces a `MonadProgram` typeclass similar to the `MonadFree` typeclass, and makes integrating `operational` into any monad transformer stack nicer to work with.

Would this be something you'd like to have directly in your package?

**Comment by srijs** [comment]
ping @HeinrichApfelmus?

**Comment by HeinrichApfelmus** [comment]
Hm, I don't know. An instance of the `MonadProgram` class only works with a single instruction type. However, I have always perceived `Program` as a general way to implement monads, so it should be possible to stack different monads that were individually built with `ProgramT`.

Also, I'm not entirely happy about the interplay between `Program` and monad transformers anyway. The thing is that monads can be combined in two ways: As monad transformers or by taking the disjoint union of their corresponding instruction types. Because of this redundancy, I am somewhat reluctant to add more support for monad transformers to the library.
