### ISSUE TITLE
Need ProgramT constructors to write other lifting instances

### ISSUE THREAD

**Issue by scshunt** [HeinrichApfelmus/operational#14]
I would like to write lifting instances for `ProgramT` of other monad type classes, but cannot do so because I don't have access to the constructor. One such example is the `Zoom` typeclass from `Control.Lens.Zoom`.

For now, I am just reproducing the source code with the constructors exported, but it would be nice to have that in the future.

If the cleanliness of the interface is an issue, perhaps a separate Control.Monad.Operational.Internal module?

**Comment by HeinrichApfelmus** [comment]
Actually, it should always be possible to write the necessary instances using the `viewT` function. This *is* the appropriate destructor for `ProgramT`. The `MonadReader` instance in the source code uses the constructors only because it is convenient, not because it is necessary.

I'm not familiar with Control.Lens.Zoom. Could you elaborate on the particular class that you want to implement?

**Comment by andrewthad** [comment]
@HeinrichApfelmus I just spent a while trying to write `local` (from `MonadReader`) using `viewT` instead of pattern matching, and it doesn't seem possible to me. Can you show me how this can be done? Because if it is possible, then the `Zoom` instance is certainly doable as well.

**Comment by HeinrichApfelmus** [comment]
@andrewthad 

I do not test the code below, but I believe this should do the trick:

    {-# LANGAUAGE RankNTypes, ScopedTypeVariables #-}
    import Control.Monad
    import Control.Monad.Operational
    import Control.Monad.Trans

    instance MonadReader r m => MonadReader r (ProgramT instr m) where
        ask   = lift ask
        local = liftLocal local

    liftLocal :: Monad m => (forall a. r -> m a -> m a)
        -> (r -> ProgramT instr m b -> ProgramT instr m b)
    liftLocal local r m = eval =<< local r (viewT m)
        where
        eval :: Monad m => ProgramViewT instr m c -> ProgramT instr m c
        eval (Return x)     = return x
        eval (instr :>>= k) = singleton instr >>= liftLocal local r . k

It's really just another way of writing the code that used constructors. Note that the return type of `viewT` being in the Monad `m` corresponds to the case where we handle the `Lift` constructor.

**Comment by andrewthad** [comment]
I've created a branch that attempts to use the alternative `MonadReader` instance you have provided: https://github.com/andrewthad/operational/commit/80f23e94a6302d008bdfbf52636176091438cdc3

It fails to compile with the following error:

    /home/andrew/Development/operational/src/Control/Monad/Operational.hs:315:32:
    Couldn't match type ‘m’ with ‘ProgramT instr m’
      ‘m’ is a rigid type variable bound by
          the type signature for
            liftLocal :: Monad m =>
                         (forall a. r -> m a -> m a)
                         -> r -> ProgramT instr m b -> ProgramT instr m b
          at src/Control/Monad/Operational.hs:313:21
    Expected type: ProgramT instr m (ProgramViewT instr m b)
      Actual type: m (ProgramViewT instr m b)

I don't think that this issue can be worked around. The problem is that `viewT` wraps the result in the the `ProgramT`'s inner monad `m`, and you can't get rid of the `m`. My [issue about `mapProgramT`](https://github.com/HeinrichApfelmus/operational/issues/16) illustrates a similar situation in which a function that modifies a `ProgramT` cannot be written without access to the data constructors.

**Comment by emilaxelsson** [comment]
This works for me:

```haskell
local r p = do
    v <- lift $ viewT p
    case v of
        Return a -> return a
        i :>>= k -> singleton i >>= local r . k
```

**Comment by andrewthad** [comment]
@emilaxelsson You are right. Thanks for coming up with the solution.

I guess the only remaining question is how the runtime efficiency of the two approaches differs. I don't know how a pattern match with `viewT` compares to a real pattern match on a program. I'll try to benchmark these two approaches as some point to see if `viewT` incurs a considerable slowdown or not. If it does, then it seems like exporting the data constructors would be helpful for people who want to really optimize a certain function.

**Comment by HeinrichApfelmus** [comment]
@emilaxelsson Thanks! Note that this should actually be

```haskell
local r p = do
    v <- lift $ local r (viewT p)
    case v of
        Return a -> return a
        i :>>= k -> singleton i >>= local r . k
```

You need to include a call to `local` for the base monad, otherwise the function will just be the identity function.

**Comment by emilaxelsson** [comment]
Ah, yes indeed! (It wasn't quite the identity function because of the call to `local` on `k`, but still wrong.)

**Comment by scshunt** [comment]
I'm now very skeptical that you can even do this directly, with or without the constructor, so I'm just going to close the issue based on the discussion.
